apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: my-nginx-app
data:
  default.conf: |
    server {
        listen 8090;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        location /stub_status {
            stub_status;
            allow all;
        }
        location /health {
        return 200 'healthy';
        add_header Content-Type text/plain;
        }
        location /ready {
        return 200 'ready';
        add_header Content-Type text/plain;
        }
    }
