apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: my-nginx-app
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        location /stub_status {
            stub_status;
            allow all;
        }
    }

