apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - name: http
      port: 80
      targetPort: 8090
      nodePort: 30099
    - name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 31046  # <-- explicitly added for metrics

